AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear una Maquina Virtual en EC2 usando una AMI especifica (Cloud9Ubuntu22-2025-03-26T13-17) con 2 webs"

Parameters:
  InstanceName:
    Type: String
    Default: "MV Reemplazar"
    Description: "Nombre de la instancia a crear"
  AMI:
    Type: String
    Default: "ami-0e84f97592c6b078b"
    Description: "ID de AMI"

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: "Name"
          Value: !Ref InstanceName
      ImageId: !Ref AMI
      InstanceType: "t2.micro"
      KeyName: "vockey"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: "20"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Se ejecuta con usuario root por lo que no necesita sudo
          cd /var/www/html/
          git clone https://github.com/yumilr/websimple.git
          git clone https://github.com/yumilr/webplantilla.git
          ls -l

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Permitir trafico SSH y HTTP desde cualquier lugar"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"

Outputs:
  InstanceId:
    Description: "ID de la instancia EC2"
    Value: !Ref EC2Instance
  InstancePublicIP:
    Description: "IP publica de la instancia"
    Value: !GetAtt EC2Instance.PublicIp
  websimpleURL:
    Description: "URL de websimple"
    Value: !Sub "http://${EC2Instance.PublicIp}/websimple"
  webplantillaURL:
    Description: "URL de webplantilla"
    Value: !Sub "http://${EC2Instance.PublicIp}/webplantilla/salient"
